### ISSUE TITLE
diag.js incomplete

### ISSUE THREAD

**Issue by jmg421** [ctrezevant/speedRacer#1]
haven't used git before but getting started with it.  thought it would be worth mentioning there is a small issue with diag.js, it needs to have parseConfig() run around line 58

**Comment by chtzvt** [comment]
Hey, John! Thanks for dropping by. 

You're absolutely correct in noticing that [diag.js](https://github.com/ctrezevant/speedRacer/blob/master/Sources/System%20Diagnostics/diag.js) does not properly instantiate the board hardware before use. 

A "fixed" version of that file might exist in the [system image for version 1](https://github.com/ctrezevant/speedRacer/blob/master/System%20Images/SpeedRacer1.0.zip), but it's hard to say as I don't really maintain this project anymore. I can definitely recall using it in a working state as I was troubleshooting some problems with the wiring during initial installation, but it's very likely that those changes may have been lost to the ether one way or another (in all honesty, like most high school-era projects, I ended up finishing speedRacer in only barely enough time for its actual production use).

While this repository is most likely going to continue on being largely unmaintained, I did notice that its [forks](https://github.com/ctrezevant/speedRacer/network/members) had grown- it seems that @calebmcelroy has a [speedRacer fork](https://github.com/calebmcelroy/speedRacer) that he's been been actively doing development on, and a cursory look through the code reveals a variety of performance improvements and enhancements to the project. While I definitely appreciate the interest in the speedRacer project here in my original repo, I'd definitely recommend that future contributions be directed towards his fork. There's a possibility that he might open a pull request to merge those changes into this repo, but that'd ultimately be up to him to share those changes (and even then, I still wouldn't be able to develop it further).

On a slight tangent- Welcome to Git/Github! If you're new and looking for some useful resources to get started, have a look at some of my documentation here: [ctis.me/s/git](https://www.ctis.me/s/git/)

Best regards, and thanks for reaching out!
