### ISSUE TITLE
Corrections in diag.js

### ISSUE THREAD

**Issue by DevDavidW** [ctrezevant/speedRacer#2]
The declaration of raspi needs to be updated to:
var raspi = require('raspi-io').RaspiIO;

In the ready function, need to call parseConfig(); at the beginning.

**Comment by chtzvt** [comment]
Hey David, 

Nice catch! Would you mind opening a pull request with your corrections? I'd be more than happy to merge :)

**Comment by chtzvt** [comment]
Closing this, as #3 and #4 have been merged. Thanks again!! :)
